spring:
  data:
    mongodb:
      host: localhost        # MongoDB server host
      port: 27017             # MongoDB server port
      database: practice        # Database name
  jackson:
    serialization:
      write-dates-as-timestamps: false  # Use ISODate format for Date objects

# Additional configurations (optional)
logging:
  level:
    org.springframework.data.mongodb: DEBUG  # Set log level for MongoDB-related logs